version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    steps:
      - node/build
  test:
    steps:
      - node/test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test